export function governanceModel(d={}){
  const assumptions=Array.isArray(d.assumptions)?d.assumptions:[];
  const evidence=Array.isArray(d.evidence)?d.evidence:[];
  const alternatives=Array.isArray(d.alternatives||d.options)?(d.alternatives||d.options):[];
  const contradictions=Array.isArray(d.contradictions)?d.contradictions.filter(c=>!['resolved','accepted','dismissed'].includes(String(c.status||'').toLowerCase())):[];
  const critical=assumptions.filter(a=>(a.leapOfFaith||a.leap_of_faith||Number(a.criticality||0)>=.75||Number(a.impact||a.importance||0)*Number(a.uncertainty||0)>=16)&&!['validated','supported'].includes(String(a.status||'').toLowerCase()));
  const strength={strong:1,high:1,medium:.65,moderate:.65,weak:.3,low:.2};
  const quality=evidence.length?evidence.reduce((s,e)=>s+(strength[String(e.strength||'').toLowerCase()]??.5),0)/evidence.length:0;
  const covered=assumptions.filter(a=>Array.isArray(a.evidenceIds)&&a.evidenceIds.length||Array.isArray(a.evidence)&&a.evidence.length).length;
  const coverage=assumptions.length?covered/assumptions.length:(evidence.length?1:0);
  const unresolvedDissent=Array.isArray(d.dissent)?d.dissent.filter(x=>x.unresolved!==false):[];
  const conditions=Array.isArray(d.approvalConditions||d.approval_conditions)?(d.approvalConditions||d.approval_conditions):[];
  const pendingConditions=conditions.filter(x=>String(x.status||'pending')==='pending');
  const conf=Number.isFinite(Number(d.governance?.confidence))?Number(d.governance.confidence):Math.max(0,Math.min(1,.5*quality+.25*coverage+.15*Math.min(1,alternatives.length/3)+.1*(critical.length?0:.7)-Math.min(.35,(contradictions.length)*.08)));
  const workflowState=d.workflowState||d.workflow_state||'DRAFT';
  const rigor=d.governance?.rigor||d.rigorLevel||d.decisionContext?.decisionRigor||d.decisionContext?.requiredEvidenceLevel||'standard';
  const next=critical.length?`Test the highest-impact assumption: ${critical.sort((a,b)=>(Number(b.impact||0)*Number(b.uncertainty||0))-(Number(a.impact||0)*Number(a.uncertainty||0)))[0]?.text||'critical assumption'}`:contradictions.some(c=>['high','critical'].includes(String(c.severity||'').toLowerCase()))?'Resolve the highest-severity contradiction before approval.':pendingConditions.length?'Verify the remaining approval conditions.':workflowState==='READY_FOR_REVIEW'?'Complete reviewer sign-off.':workflowState==='APPROVED'?'Start the approved execution plan.':workflowState==='EXECUTING'?'Monitor the experiment and record the outcome.':workflowState==='OBSERVING'?'Capture the observed outcome and learning.':workflowState==='LEARNED'?'Archive or reuse this decision learning.':'Strengthen evidence and assumptions before review.';
  return {workflowState,rigor,evidenceCount:evidence.length,evidenceQuality:quality,evidenceCoverage:coverage,criticalOpen:critical.length,contradictions,alternatives:alternatives.length,unresolvedDissent,pendingConditions,confidence:conf,approvalConditions:conditions,whatWouldChangeMyMind:Array.isArray(d.whatWouldChangeMyMind||d.what_would_change_my_mind)?(d.whatWouldChangeMyMind||d.what_would_change_my_mind):[],expiryAt:d.expiryAt||d.expiry_at||null,reviewDueAt:d.reviewDueAt||d.review_due_at||null,reviewStatus:d.reviewStatus||d.review_status||'not_started',next};
}

export function renderStage4Governance(d,esc){
  const g=governanceModel(d);
  const pct=x=>Math.round(x*100);
  const conditions=(g.approvalConditions.length?g.approvalConditions:[{metric:'Recovery rate',operator:'gte',targetValue:10,status:'pending',unit:'relative %'}]);
  const mind=(g.whatWouldChangeMyMind.length?g.whatWouldChangeMyMind:['New evidence materially lowers recovery intent','Guardrail metric exceeds agreed threshold']);
  const history=(d.workflowHistory||[]).slice().reverse().slice(0,8);
  const role=(d.roles?.owner||d.owner||'Decision owner');
  return `<div class="stage4-governance">
  <div class="gov-header"><div><div class="section-kicker">Decision governance</div><h2>Make the decision explicit, reviewable, and reversible when reality changes.</h2></div><span class="pill ${g.workflowState==='APPROVED'?'good':g.workflowState==='READY_FOR_REVIEW'?'good':'warn'}">${esc(g.workflowState.replaceAll('_',' '))}</span></div>
  <div class="gov-grid">
    <div class="gov-block"><div class="section-kicker">Decision policy</div><div class="gov-line"><strong>Rigor</strong><select id="govRigor"><option value="quick" ${g.rigor==='quick'||g.rigor==='minimal'?'selected':''}>Quick</option><option value="standard" ${g.rigor==='standard'||g.rigor==='moderate'?'selected':''}>Standard</option><option value="significant" ${g.rigor==='significant'||g.rigor==='high'?'selected':''}>Significant</option><option value="high_stakes" ${g.rigor==='high_stakes'||g.rigor==='maximum'?'selected':''}>High stakes</option></select></div><div class="note">Higher rigor raises evidence, review, and approval requirements.</div><div class="gov-line"><strong>Owner</strong><span>${esc(role)}</span></div><div class="gov-line"><strong>Review status</strong><span>${esc(g.reviewStatus.replaceAll('_',' '))}</span></div><div class="gov-line"><strong>Review due</strong><input id="govReviewDue" type="date" value="${g.reviewDueAt?esc(String(g.reviewDueAt).slice(0,10)):''}"></div><div class="gov-line"><strong>Expiry</strong><input id="govExpiry" type="date" value="${g.expiryAt?esc(String(g.expiryAt).slice(0,10)):''}"></div></div>
    <div class="gov-block"><div class="section-kicker">Decision signal</div><div class="gov-score"><strong>${pct(g.confidence)}%</strong><span>confidence</span></div><div class="gov-metrics"><div><strong>${pct(g.evidenceQuality)}%</strong><span>evidence quality</span></div><div><strong>${pct(g.evidenceCoverage)}%</strong><span>assumption coverage</span></div><div><strong>${g.criticalOpen}</strong><span>critical open</span></div><div><strong>${g.contradictions.length}</strong><span>open conflict</span></div></div><div class="next-action"><strong>Next best action</strong><span>${esc(g.next)}</span></div></div>
  </div>
  <div class="gov-grid">
    <div class="gov-block"><div class="section-kicker">Why blocked / what matters</div>${g.criticalOpen?`<div class="gate-row blocked"><span>!</span><span>${g.criticalOpen} critical assumption(s) still open.</span></div>`:''}${g.contradictions.filter(c=>['high','critical'].includes(String(c.severity||'').toLowerCase())).map(c=>`<div class="gate-row blocked"><span>!</span><span>${esc(c.explanation||'High-severity contradiction requires review.')}</span></div>`).join('')||''}${g.pendingConditions.length?`<div class="gate-row blocked"><span>!</span><span>${g.pendingConditions.length} approval condition(s) pending.</span></div>`:''}${!g.criticalOpen&&!g.contradictions.length&&!g.pendingConditions.length?'<div class="gate-row clear"><span>✓</span><span>No current governance blockers.</span></div>':''}</div>
    <div class="gov-block"><div class="section-kicker">What would change our mind?</div>${mind.map((x,i)=>`<div class="gov-line"><span>${i+1}</span><input class="gov-mind" data-index="${i}" value="${esc(typeof x==='string'?x:x.text||'')}"><button class="btn ghost gov-remove-mind" data-index="${i}">Remove</button></div>`).join('')}<button class="btn ghost" id="govAddMind">+ Add condition</button></div>
  </div>
  <div class="gov-grid">
    <div class="gov-block"><div class="section-kicker">Approval conditions</div>${conditions.map((c,i)=>`<div class="gov-condition"><input class="gov-cond-metric" data-index="${i}" value="${esc(c.metric||'')}"><select class="gov-cond-op" data-index="${i}"><option value="gt" ${c.operator==='gt'?'selected':''}>></option><option value="gte" ${c.operator==='gte'?'selected':''}>>=</option><option value="lt" ${c.operator==='lt'?'selected':''}><</option><option value="lte" ${c.operator==='lte'?'selected':''}><=</option><option value="eq" ${c.operator==='eq'?'selected':''}>=</option><option value="between" ${c.operator==='between'?'selected':''}>between</option></select><input class="gov-cond-target" data-index="${i}" type="number" value="${c.targetValue??''}" placeholder="target"><span class="pill ${c.status==='met'?'good':c.status==='not_met'?'bad':'warn'}">${esc(c.status||'pending')}</span></div>`).join('')}<button class="btn ghost" id="govAddCondition">+ Add condition</button></div>
    <div class="gov-block"><div class="section-kicker">Review & dissent</div><div class="gov-review-actions"><button class="btn" id="govRequestReview">Request review</button><button class="btn primary" id="govApprove">Approve</button><button class="btn" id="govReopen">Reopen</button></div><div class="note">Approval remains human-controlled. AI may flag blockers or propose actions but cannot approve.</div>${g.unresolvedDissent.map(x=>`<div class="dissent"><strong>${esc(x.author||x.authorId||'Reviewer')}</strong><span>${esc(x.stance||'request_changes')}</span><p>${esc(x.reason||'')}</p></div>`).join('')||'<div class="note">No unresolved dissent recorded.</div>'}<button class="btn ghost" id="govAddDissent">+ Capture dissent</button></div>
  </div>
  <div class="gov-grid">
    <div class="gov-block"><div class="section-kicker">Decision history</div>${history.map(h=>`<div class="history-row"><strong>${esc((h.to||h.event||'changed').replaceAll('_',' '))}</strong><span>${esc(h.reason||'')} · ${esc(h.at||h.createdAt||'')}</span></div>`).join('')||'<div class="note">No workflow history yet.</div>'}<button class="btn ghost" id="govSnapshot">Capture governed snapshot</button></div>
    <div class="gov-block"><div class="section-kicker">Decision contract</div><pre class="gov-contract">${esc(JSON.stringify({decisionId:d.id,title:d.title,workflowState:g.workflowState,rigor:g.rigor,confidence:g.confidence,criticalOpen:g.criticalOpen,evidenceQuality:g.evidenceQuality,evidenceCoverage:g.evidenceCoverage,approvalConditions:conditions,whatWouldChangeMyMind:mind,expiryAt:g.expiryAt,reviewDueAt:g.reviewDueAt},null,2))}</pre></div>
  </div>
  </div>`;
}

export function bindStage4Governance({state,current,commit,track,render,toast,openModal,closeModal}){
  const d=current(); if(!d)return;
  d.governance=d.governance||{};
  const set=(k,v)=>{d.governance[k]=v;commit(`Governance ${k} updated`);track('decision_governance_changed',{decision_id:d.id,field:k});render()};
  document.querySelector('#govRigor')?.addEventListener('change',e=>set('rigor',e.target.value));
  document.querySelector('#govReviewDue')?.addEventListener('change',e=>set('reviewDueAt',e.target.value?new Date(e.target.value+'T00:00:00Z').toISOString():null));
  document.querySelector('#govExpiry')?.addEventListener('change',e=>set('expiryAt',e.target.value?new Date(e.target.value+'T00:00:00Z').toISOString():null));
  document.querySelector('#govAddMind')?.addEventListener('click',()=>{d.whatWouldChangeMyMind=Array.isArray(d.whatWouldChangeMyMind)?d.whatWouldChangeMyMind:[];d.whatWouldChangeMyMind.push('');commit('Mind-change condition added');render()});
  document.querySelectorAll('.gov-mind').forEach(x=>x.addEventListener('change',e=>{d.whatWouldChangeMyMind=Array.isArray(d.whatWouldChangeMyMind)?d.whatWouldChangeMyMind:[];d.whatWouldChangeMyMind[Number(e.target.dataset.index)]=e.target.value.trim();commit('Decision condition updated');render()}));
  document.querySelectorAll('.gov-remove-mind').forEach(x=>x.addEventListener('click',()=>{d.whatWouldChangeMyMind.splice(Number(x.dataset.index),1);commit('Mind-change condition removed');render()}));
  document.querySelector('#govAddCondition')?.addEventListener('click',()=>{d.approvalConditions=Array.isArray(d.approvalConditions)?d.approvalConditions:[];d.approvalConditions.push({metric:'',operator:'gte',targetValue:'',status:'pending'});commit('Approval condition added');render()});
  document.querySelectorAll('.gov-cond-metric').forEach(x=>x.addEventListener('change',e=>{const i=Number(e.target.dataset.index);d.approvalConditions[i].metric=e.target.value;commit('Condition metric updated');render()}));
  document.querySelectorAll('.gov-cond-op').forEach(x=>x.addEventListener('change',e=>{const i=Number(e.target.dataset.index);d.approvalConditions[i].operator=e.target.value;commit('Condition operator updated');render()}));
  document.querySelectorAll('.gov-cond-target').forEach(x=>x.addEventListener('change',e=>{const i=Number(e.target.dataset.index);d.approvalConditions[i].targetValue=Number(e.target.value);commit('Condition target updated');render()}));
  document.querySelector('#govRequestReview')?.addEventListener('click',()=>{stageTransitionLocal(d,'READY_FOR_REVIEW','review_requested');track('decision_review_requested',{decision_id:d.id});render()});
  document.querySelector('#govApprove')?.addEventListener('click',()=>{const g=governanceModel(d);if(g.workflowState!=='READY_FOR_REVIEW')return toast('Submit the decision for review first.');if(!confirm('Approve this decision and lock its current reasoning snapshot?'))return;stageTransitionLocal(d,'APPROVED','approved');d.approvedAt=new Date().toISOString();d.approvedSnapshot=d.approvedSnapshot||{capturedAt:new Date().toISOString(),decision:structuredClone(d)};track('decision_approved_local',{decision_id:d.id});render()});
  document.querySelector('#govReopen')?.addEventListener('click',()=>{const reasons=['new_evidence','assumption_invalidated','outcome_changed','stakeholder_change','external_condition','policy_change','data_correction','implementation_change','other'];openModal(`<div class="pad"><div class="section-head"><h2>Reopen decision</h2><button class="btn ghost" id="mc">Close</button></div><div class="form"><div class="field"><label>Reason</label><select id="reopenReason">${reasons.map(x=>`<option value="${x}">${x.replaceAll('_',' ')}</option>`).join('')}</select></div><div class="field"><label>What changed?</label><textarea id="reopenText" placeholder="Describe the new evidence, outcome, or condition."></textarea></div><button class="btn primary" id="confirmReopen">Reopen</button></div></div>`);document.querySelector('#mc').onclick=closeModal;document.querySelector('#confirmReopen').onclick=()=>{d.governance.reopenReason=document.querySelector('#reopenReason').value;d.governance.reopenNote=document.querySelector('#reopenText').value.trim();stageTransitionLocal(d,'INVESTIGATING','reopened');d.reopenCount=(d.reopenCount||0)+1;commit('Decision reopened');track('decision_reopened',{decision_id:d.id,reason_code:d.governance.reopenReason});closeModal();render()}});
  document.querySelector('#govAddDissent')?.addEventListener('click',()=>openModal(`<div class="pad"><div class="section-head"><h2>Capture dissent</h2><button class="btn ghost" id="mc">Close</button></div><div class="form"><div class="field"><label>Stance</label><select id="ds"><option>request_changes</option><option>reject</option><option>abstain</option><option>approve</option></select></div><div class="field"><label>Reason</label><textarea id="dt"></textarea></div><button class="btn primary" id="saveDissent">Capture</button></div></div>`),document.querySelector('#mc').onclick=closeModal,document.querySelector('#saveDissent').onclick=()=>{d.dissent=Array.isArray(d.dissent)?d.dissent:[];d.dissent.push({author:state.user?.email||'Current user',stance:document.querySelector('#ds').value,reason:document.querySelector('#dt').value.trim(),unresolved:true,createdAt:new Date().toISOString()});commit('Dissent captured');track('decision_dissent_added',{decision_id:d.id});closeModal();render()});
  document.querySelector('#govSnapshot')?.addEventListener('click',()=>{d.workflowHistory=d.workflowHistory||[];d.governanceSnapshots=d.governanceSnapshots||[];const snap={version:d.workflowStateVersion||1,state:d.workflowState||'DRAFT',capturedAt:new Date().toISOString(),decision:structuredClone(d)};d.governanceSnapshots.push(snap);commit('Governed decision snapshot captured');track('decision_governance_snapshot',{decision_id:d.id,version:snap.version});render()});
}
function stageTransitionLocal(d,to,reason){const from=d.workflowState||'DRAFT';d.workflowHistory=d.workflowHistory||[];d.workflowHistory.push({from,to,reason,at:new Date().toISOString()});d.workflowState=to;d.workflowStateVersion=(d.workflowStateVersion||1)+1;d.governance=d.governance||{};d.governance.lastTransitionReason=reason;d.governance.lastTransitionAt=new Date().toISOString();}
