const test=require('node:test');
const assert=require('node:assert/strict');
const {classifyQuestion,classifyQuestionDetailed,methodFit,evidenceQuality,evidenceGaps,detectContradictions,triangulation,opportunityScore,assumptionRisk,generateAssumptions,generateSolutions,discoveryGate,analyzeDiscovery}=require('../lib/productDiscovery');
test('question understanding and method fit are explicit',()=>{assert.equal(classifyQuestion('Why do users abandon onboarding?'),'causal');assert.equal(classifyQuestionDetailed('How often do users abandon?').type,'descriptive');assert.equal(methodFit('causal','experiment').fit,'HIGH');assert.equal(methodFit('causal','survey').fit,'LOW');assert.ok(methodFit('causal','experiment').recommended.length>0)});
test('evidence quality exposes multiple dimensions without hiding uncertainty',()=>{const q=evidenceQuality([{id:'e1',content:'Users reported the flow is confusing.',sourceType:'interview',participantId:'p1',segment:'new',sourceId:'I-1',quote:'confusing',strength:'medium'}]);assert.equal(q.items.length,1);assert.ok(q.items[0].qualityDimensions.sourceReliability>0);assert.ok(q.items[0].quality>=0&&q.items[0].quality<=1)});
test('contradictions are surfaced with human-review context',()=>{const x=detectContradictions([{id:'e1',content:'users want more customization',stance:'supports',segment:'new'},{id:'e2',content:'users do not want customization',stance:'contradicts',segment:'new'}]);assert.equal(x.length,1);assert.equal(x[0].requiresHumanReview,true)});
test('triangulation distinguishes single, multi-method and converging evidence',()=>{assert.equal(triangulation([{sourceType:'interview'}]).status,'SINGLE_METHOD');assert.equal(triangulation([{sourceType:'interview'},{sourceType:'analytics'}]).status,'TRIANGULATED');assert.equal(triangulation([{sourceType:'interview'},{sourceType:'analytics'},{sourceType:'support'}]).status,'CONVERGING')});
test('opportunity and assumption scores are bounded and transparent',()=>{const o=opportunityScore({customerImportance:10,customerReach:0,strategicRelevance:10,evidenceStrength:10,marketRelevance:10,confidence:1});assert.ok(o>=0&&o<=10);const r=assumptionRisk({importance:10,uncertainty:10,evidenceStrength:0,costOfError:10});assert.equal(r,100)});
test('evidence gaps are typed by question requirements',()=>{const g=evidenceGaps({questionType:'causal',evidence:[],quality:{aggregate:0},contradictions:[],decisionImpact:'high'});assert.ok(g.some(x=>x.requirement==='counterfactual/comparator'));assert.ok(g.some(x=>x.severity==='high'))});
test('discovery gate blocks missing core inputs and investigates evidence gaps',()=>{const x=discoveryGate({desiredOutcome:'activate users',researchQuestion:'Why do users abandon?',method:'interview',evidence:[]});assert.equal(x.status,'INVESTIGATE');assert.ok(x.warnings.includes('insufficient_evidence'))});
test('end-to-end discovery analysis materializes downstream decision inputs',()=>{const x=analyzeDiscovery({id:'disc-1',desiredOutcome:'increase activation',researchQuestion:'Why do users abandon onboarding?',method:'interview',evidence:[{id:'e1',content:'The setup is confusing and I left.',sourceType:'interview',stance:'supports',segment:'new',participantId:'p1',sourceId:'I1',quote:'confusing'},{id:'e2',content:'I used a spreadsheet workaround.',sourceType:'support_ticket_analysis',stance:'supports',segment:'new',participantId:'p2',sourceId:'S1'},{id:'e3',content:'Setup is easy after the first use.',sourceType:'usability_test',stance:'contradicts',segment:'power',participantId:'p3',sourceId:'U1'}]});assert.equal(x.questionType,'causal');assert.ok(x.themes.length>0);assert.ok(x.opportunities.length>0);assert.ok(x.solutions.length>=x.opportunities.length);assert.ok(x.assumptions.length>0);assert.equal(x.ost.type,'outcome');assert.ok(Array.isArray(x.downstream.experimentSeeds));assert.equal(x.gate.status,'INVESTIGATE')});
test('generated solutions and assumptions preserve the discovery lineage',()=>{const ops=[{id:'O1',label:'friction',score:8,confidence:.4,evidenceIds:['e1']}];const a=generateAssumptions(ops);const s=generateSolutions(ops);assert.equal(a[0].opportunityId,'O1');assert.equal(s[0].opportunityId,'O1')});

const {analyzeDiscoverySemantically}=require('../lib/productDiscovery');
test('semantic contracts fail closed on unknown evidence references',async()=>{await assert.rejects(()=>analyzeDiscoverySemantically({desiredOutcome:'increase activation',researchQuestion:'Why do users abandon?',evidence:[{id:'E1',content:'Users report friction.',sourceType:'interview'}]},{callSemanticModel:async()=>({questionUnderstanding:{type:'causal',confidence:.9,decisionImpact:'high',intentRationale:'cause',ambiguities:[],evidenceRequirements:['counterfactual']},methodFit:{method:'interview',score:3,confidence:.7,rationale:'partial',decisionNeed:'cause',alternatives:[]},codes:[{id:'C1',type:'pain_point',label:'friction',evidenceIds:['E9'],confidence:.8}],themes:[],claims:[],contradictions:[],evidenceGaps:[],triangulation:{status:'SINGLE_METHOD',rationale:'one source',confidence:.2},opportunities:[],assumptions:[],solutions:[],nextActions:[]})}),/Semantic discovery contract failed/);});

test('semantic enrichment requires a model adapter and cannot silently fall back',async()=>{await assert.rejects(()=>analyzeDiscoverySemantically({desiredOutcome:'x',researchQuestion:'why?',evidence:[]}),/adapter is required/)});
test('semantic evidence references are allowlisted to supplied evidence',async()=>{const out=await analyzeDiscoverySemantically({desiredOutcome:'increase activation',researchQuestion:'Why do users abandon?',method:'interview',evidence:[{id:'E1',content:'Users report friction in setup.',sourceType:'interview',participantId:'p1',sourceId:'I1'}]},{callSemanticModel:async()=>({questionUnderstanding:{type:'diagnostic',confidence:.9,decisionImpact:'high',intentRationale:'diagnostic',ambiguities:[],evidenceRequirements:['alternative explanations']},methodFit:{method:'interview',score:4,confidence:.8,rationale:'Useful exploratory input',decisionNeed:'understand cause',alternatives:[]},codes:[{id:'C1',type:'pain_point',label:'setup friction',evidenceIds:['E1'],confidence:.8}],themes:[{id:'T1',label:'setup friction',description:'Repeated setup friction',evidenceIds:['E1'],confidence:.8}],contradictions:[],evidenceGaps:['behavioral data'],triangulation:{status:'SINGLE_METHOD',rationale:'one source type',confidence:.3},opportunities:[{id:'O1',label:'reduce setup friction',rationale:'supported by E1',evidenceIds:['E1'],themeIds:['T1'],segments:['new'],confidence:.8}],assumptions:[{id:'A1',text:'Reducing setup friction improves activation',opportunityId:'O1',evidenceIds:['E1'],assumptionType:'desirability',importance:8,uncertainty:7,leapOfFaith:true}],solutions:[{id:'S1',opportunityId:'O1',title:'Guided setup',description:'Guide users',evidenceIds:['E1'],rationale:'addresses friction'}],nextActions:['Collect behavioral analytics'],model:'test-model',promptVersion:'test-v1'})});assert.equal(out.semantic.mode,'llm_verified');assert.ok(!out.opportunities[0].evidenceIds.includes('BAD'));assert.equal(out.opportunities[0].semanticVerification.unsupported,false);});
