const test=require('node:test');
const assert=require('node:assert/strict');
const {buildDeepResearchQueries,tavilySearch,runDeepWebSweep}=require('../lib/deepResearchWeb');

test('deep research creates focused multi-query search plan',()=>{const q=buildDeepResearchQueries({question:'Should onboarding change?',desiredOutcome:'increase activation',segments:['SMB'],sourceClasses:['academic','competitor','customer_voice']});assert.ok(q.length>=4);assert.ok(q.some(x=>/academic/i.test(x)));assert.ok(q.some(x=>/competitor/i.test(x)));});
test('tavily adapter maps provider results into normalized research sources',async()=>{const fake=async()=>({ok:true,json:async()=>({request_id:'r1',results:[{url:'https://example.com/a',title:'A',content:'Evidence',score:.91}]})});const r=await tavilySearch('test',{apiKey:'tvly-test',fetchImpl:fake});assert.equal(r.length,1);assert.equal(r[0].url,'https://example.com/a');assert.equal(r[0].relevance,.91);});
test('deep web sweep deduplicates repeated URLs and retains provider failures',async()=>{let calls=0;const fake=async()=>{calls++;return {ok:true,json:async()=>({results:[{url:'https://example.com/shared',title:'Shared',content:'Evidence',score:.9},{url:`https://example.com/${calls}`,title:`Unique ${calls}`,content:'Evidence',score:.8}]})}};const r=await runDeepWebSweep({researchQuestion:'test question',desiredOutcome:'test outcome',questionType:'exploratory',segments:['SMB']},{apiKey:'tvly-test',fetchImpl:fake,concurrency:2});assert.ok(calls>=4);assert.equal(r.duplicates.length>0,true);assert.ok(r.independentCount>=2);});

const {researchSaturation,scoreQuestionQuality}=require('../lib/productDiscovery');
test('deep research propagates source class and detects low-novelty saturation',async()=>{let calls=0;const fake=async()=>{calls++;const n=calls;return {ok:true,json:async()=>({results:[{url:`https://publisher${n}.example/a`,title:'Onboarding friction',content:'users activation onboarding friction repeated',score:.9}]})}};const r=await runDeepWebSweep({researchQuestion:'onboarding friction',desiredOutcome:'increase activation',questionType:'exploratory',segments:['SMB']},{apiKey:'x',fetchImpl:fake,concurrency:2});assert.ok(r.retained.some(x=>x.sourceClass==='primary_research'));const sat=researchSaturation({orderedSources:r.retained,themesBefore:[],themesAfter:r.retained.map(x=>({label:'onboarding friction'}))});assert.equal(typeof sat.noveltyRatio,'number');assert.ok(calls>=4)});
test('question quality detects missing decision framing dimensions',()=>{const r=scoreQuestionQuality('What do users think?',{targetSegments:[]});assert.ok(r.issues.includes('scope_or_segment_unclear'));assert.ok(r.dimensions.measurability<.7);});
