'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..');

test('Stage 4 legacy migration contains the original governance APIs',()=>{for(const f of ['db/migrations/024_stage4_canonical_governance.sql','supabase/migration_024_stage4_canonical_governance.sql']){const s=fs.readFileSync(path.join(root,f),'utf8');for(const token of ['thinkforge_decision_governance','thinkforge_decision_governance_policy_v1','thinkforge_decision_readiness_v1','thinkforge_decision_readiness_v2','thinkforge_transition_decision_v2','thinkforge_approve_decision_v1','thinkforge_reopen_decision_v1'])assert.ok(s.includes(token),`missing ${token} in ${f}`);assert.equal(s.includes('thinkforge_options'),false);}});

test('Stage 4 consolidation migration contains only forward-compatibility adapters and final hardening marker',()=>{for(const f of ['db/migrations/025_stage4_governance_consolidation.sql','supabase/migration_025_stage4_governance_consolidation.sql']){const s=fs.readFileSync(path.join(root,f),'utf8');for(const token of ['thinkforge_decision_readiness_v3','thinkforge_transition_decision_v3','thinkforge_approve_decision_v2','thinkforge_reopen_decision_v2','stage4-v4'])assert.ok(s.includes(token),`missing ${token} in ${f}`);assert.equal(s.includes('thinkforge_options'),false);}});

test('Stage 4 finalization migration defines the single authoritative policy boundary',()=>{for(const f of ['db/migrations/026_stage4_governance_finalization.sql','supabase/migration_026_stage4_governance_finalization.sql']){const s=fs.readFileSync(path.join(root,f),'utf8');for(const token of ['thinkforge_decision_transition_policies','thinkforge_decision_transition_policy_v2','thinkforge_decision_readiness_v4','thinkforge_transition_decision_v4','stage4-v4'])assert.ok(s.includes(token),`missing ${token} in ${f}`);const readinessStart=s.indexOf('create or replace function public.thinkforge_decision_readiness_v4'); const readinessEnd=s.indexOf('create or replace function public.thinkforge_decision_readiness_v3'); const readinessBody=s.slice(readinessStart,readinessEnd);assert.doesNotMatch(readinessBody,/thinkforge_decision_readiness_v[123]\s*\(/);const transitionStart=s.indexOf('create or replace function public.thinkforge_transition_decision_v4'); const transitionEnd=s.indexOf('create or replace function public.thinkforge_transition_decision_v3'); const transitionBody=s.slice(transitionStart,transitionEnd);assert.doesNotMatch(transitionBody,/thinkforge_transition_decision_v[123]\s*\(/);assert.equal(s.includes('thinkforge_options'),false);}});

test('governance API delegates persisted authority to the final canonical DB RPCs',()=>{const s=fs.readFileSync(path.join(root,'api/decision-governance.js'),'utf8');assert.equal(s.includes("approvalDecision({"),false);assert.equal(s.includes("reopenDecision({"),false);assert.equal(s.includes("b.role||'viewer'"),false);assert.match(s,/thinkforge_approve_decision_v2/);assert.match(s,/thinkforge_reopen_decision_v2/);assert.match(s,/thinkforge_transition_decision_v4/);assert.match(s,/thinkforge_decision_readiness_v4/);});

test('legacy workflow module is a compatibility facade',()=>{const s=fs.readFileSync(path.join(root,'lib/decisionWorkflow.js'),'utf8');assert.match(s,/require\('\.\/decisionGovernance'\)/);assert.ok(!s.includes('function confidenceBreakdown(decision'));assert.ok(!s.includes('function assumptionPriority'));});

test('legacy decision API contains no direct legacy governance RPC calls',()=>{const s=fs.readFileSync(path.join(root,'api/decision.js'),'utf8');for(const pattern of [/thinkforge_decision_readiness_v1/,/thinkforge_decision_readiness_v2/,/thinkforge_decision_readiness_v3/,/thinkforge_transition_decision_v1/,/thinkforge_transition_decision_v2/,/thinkforge_transition_decision_v3/,/thinkforge_approve_decision_v1/,/thinkforge_reopen_decision_v1/])assert.doesNotMatch(s,pattern);});
