const test=require('node:test');
const assert=require('node:assert/strict');
const {DEEP_RESEARCH_POLICY,discoveryResearchPlan,normalizeResearchSource,dedupeResearchSources,sourceDiversity,humanResearchEvidence,deepResearchQuality,buildDeepResearchReport}=require('../lib/productDiscovery');

function sources(n=60){return Array.from({length:n},(_,i)=>({id:`S${i}`,url:`https://source-${i}.example/research/${i}`,title:`Independent research ${i} alpha${i}`,sourceClass:['academic','industry_report','primary_research','customer_voice','government_regulatory','technical_publication'][i%6],content:`Independent evidence about onboarding friction source-specific finding alpha${i} beta${i} gamma${i} delta${i}`,authority:.85,relevance:.9,methodTransparency:.8}));}

test('deep research policy targets 60 independent sources and 40 minimum',()=>{assert.equal(DEEP_RESEARCH_POLICY.targetSources,60);assert.equal(DEEP_RESEARCH_POLICY.minimumIndependentSources,40);});
test('research planner selects deep mode for high impact questions',()=>{const p=discoveryResearchPlan({question:'Should we change onboarding?',questionType:'evaluative',decisionImpact:'high',segments:['SMB'],desiredOutcome:'increase activation'});assert.equal(p.depth,'deep');assert.equal(p.targetSources,60);assert.equal(p.minimumIndependentSources,40);assert.ok(p.sourceClasses.includes('customer_voice'));});
test('source normalization produces quality and independence keys',()=>{const s=normalizeResearchSource({url:'https://Example.com/a?x=1',title:'A',sourceClass:'academic',content:'method'});assert.equal(s.sourceClass,'academic');assert.ok(s.quality>.5);assert.equal(s.independenceKey,'example.com/a');});
test('related URLs sharing underlying study are not counted as independent',()=>{const r=dedupeResearchSources([{id:'A',url:'https://a.test',underlyingSourceId:'STUDY-1',sourceClass:'academic'},{id:'B',url:'https://b.test',underlyingSourceId:'STUDY-1',sourceClass:'news_media'},{id:'C',url:'https://c.test',underlyingSourceId:'STUDY-2',sourceClass:'academic'}]);assert.equal(r.independentCount,2);assert.equal(r.duplicates.length,1);});
test('source diversity measures independent source classes',()=>{const r=sourceDiversity(sources(12));assert.equal(r.occupiedClasses,6);assert.ok(r.diversityScore>=.95);});
test('human research requires provenance and consent for empirical evidence',()=>{const r=humanResearchEvidence([{id:'H1',participantId:'P1',response:'Setup was confusing',method:'interview',segment:'SMB',consentRecorded:true,sourceId:'SESSION-1'},{id:'H2',synthetic:true,response:'I would prefer a simpler setup'}]);assert.equal(r[0].evidenceStatus,'REAL_HUMAN_EVIDENCE');assert.equal(r[0].usableForEmpiricalClaims,true);assert.equal(r[1].evidenceStatus,DEEP_RESEARCH_POLICY.syntheticHumanLabel);assert.equal(r[1].usableForEmpiricalClaims,false);});
test('deep research quality reaches source target only with independent retained sources',()=>{const r=deepResearchQuality({sources:sources(60),humanEvidence:[],questionQuality:{score:.9},contradictions:[]});assert.equal(r.sources.independent,60);assert.equal(r.sources.targetMet,true);assert.equal(r.sources.minimumMet,true);assert.ok(r.sourceDiversity.diversityScore>=.9);});
test('deep research report excludes synthetic human responses from empirical synthesis',()=>{const r=buildDeepResearchReport({desiredOutcome:'increase activation',researchQuestion:'Why do users abandon onboarding?',questionType:'exploratory',segments:['SMB','ENT'],evidence:[{id:'E1',content:'Setup is confusing',sourceType:'interview',sourceId:'I1',segment:'SMB',participantId:'P1'}],webSources:sources(60),humanEvidence:[...Array.from({length:10},(_,i)=>({id:`H${i+1}`,participantId:`P${i+2}`,response:'Billing setup is confusing',method:'interview',segment:'SMB',consentRecorded:true,sourceId:`SESSION-H${i+1}`})),{id:'H11',synthetic:true,response:'Users want a dashboard'}]});assert.equal(r.status,'READY_FOR_SYNTHESIS');assert.equal(r.quality.sources.independent,60);assert.equal(r.humanResearch.realEvidenceCount,10);assert.equal(r.quality.humanResearch.syntheticExcludedFromEmpiricalClaims,true);assert.ok(r.epistemicRule.includes('synthetic human responses never enter empirical evidence'));});

test('human evidence without consent or segment is not empirical',()=>{const r=humanResearchEvidence([{id:'H3',participantId:'P3',response:'Useful',method:'interview',sourceId:'SESSION-3',segment:'',consentRecorded:false}]);assert.equal(r[0].usableForEmpiricalClaims,false);});
