import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector
from django.db.migrations.operations.special import RunSQL

class CreateVectorExtension(RunSQL):
    """Enable pgvector only on PostgreSQL; SQLite is used for isolated unit tests."""
    def __init__(self):
        super().__init__('CREATE EXTENSION IF NOT EXISTS vector', 'DROP EXTENSION IF EXISTS vector')
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_forwards(app_label, schema_editor, from_state, to_state)
    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_backwards(app_label, schema_editor, from_state, to_state)

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        CreateVectorExtension(),
        migrations.CreateModel(name='Organization', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('name', models.CharField(max_length=200)), ('created_at', models.DateTimeField(auto_now_add=True)), ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations_created', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Document', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('name', models.CharField(max_length=300)), ('mime_type', models.CharField(blank=True, max_length=120)), ('checksum', models.CharField(max_length=64)), ('metadata', models.JSONField(default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')), ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Workspace', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('state', models.JSONField(default=dict)), ('version', models.PositiveBigIntegerField(default=1)), ('updated_at', models.DateTimeField(auto_now=True)), ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='core.organization'))]),
        migrations.CreateModel(name='Membership', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('role', models.CharField(choices=[(x, x) for x in ('owner','admin','editor','reviewer','viewer')], max_length=16)), ('created_at', models.DateTimeField(auto_now_add=True)), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thinkforge_memberships', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Decision', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('title', models.CharField(max_length=300)), ('problem', models.TextField(blank=True)), ('status', models.CharField(default='validate', max_length=32)), ('payload', models.JSONField(default=dict)), ('version', models.PositiveBigIntegerField(default=1)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.organization'))]),
        migrations.CreateModel(name='Evidence', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('source', models.CharField(max_length=500)), ('source_type', models.CharField(max_length=64)), ('content', models.TextField()), ('stance', models.CharField(default='neutral', max_length=32)), ('strength', models.CharField(default='medium', max_length=32)), ('metadata', models.JSONField(default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.decision')), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'))]),
        migrations.CreateModel(name='Experiment', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('hypothesis', models.TextField()), ('design', models.JSONField(default=dict)), ('outcome', models.JSONField(default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.decision')), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'))]),
        migrations.CreateModel(name='Chunk', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('chunk_index', models.PositiveIntegerField()), ('content', models.TextField()), ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)), ('metadata', models.JSONField(default=dict)), ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.document')), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'))]),
        migrations.CreateModel(name='AgentRun', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('request_id', models.CharField(max_length=160)), ('state', models.CharField(choices=[(x,x) for x in ('PLANNED','AWAITING_APPROVAL','RUNNING','TOOL_CALLING','VALIDATING','RETRYING','NEEDS_HUMAN_REVIEW','COMPLETED','FAILED','CANCELLED')], default='PLANNED', max_length=32)), ('agent_version', models.CharField(max_length=80)), ('goal', models.TextField()), ('plan', models.JSONField(default=dict)), ('metrics', models.JSONField(default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.decision')), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='core.organization')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='AgentToolCall', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('tool_name', models.CharField(max_length=80)), ('status', models.CharField(max_length=32)), ('attempt', models.PositiveIntegerField(default=1)), ('input_hash', models.CharField(blank=True, max_length=64)), ('output_hash', models.CharField(blank=True, max_length=64)), ('latency_ms', models.PositiveIntegerField(default=0)), ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)), ('error_code', models.CharField(blank=True, max_length=80)), ('created_at', models.DateTimeField(auto_now_add=True)), ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='core.agentrun'))]),
        migrations.CreateModel(name='AgentStep', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('sequence_no', models.PositiveIntegerField()), ('state', models.CharField(max_length=32)), ('event_type', models.CharField(max_length=80)), ('detail', models.JSONField(default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.agentrun'))]),
        migrations.CreateModel(name='AgentFeedback', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('rating', models.PositiveSmallIntegerField(blank=True, null=True)), ('outcome', models.CharField(choices=[(x,x) for x in ('accepted','rejected','edited','inconclusive')], max_length=16)), ('note', models.TextField(blank=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.agentrun')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='AuditEvent', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('event_type', models.CharField(max_length=80)), ('entity_type', models.CharField(max_length=80)), ('entity_id', models.UUIDField(blank=True, null=True)), ('payload', models.JSONField(default=dict)), ('previous_hash', models.CharField(blank=True, max_length=64)), ('event_hash', models.CharField(max_length=64, unique=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'))]),
        migrations.AddConstraint(model_name='membership', constraint=models.UniqueConstraint(fields=('organization','user'), name='unique_org_member')),
        migrations.AddConstraint(model_name='chunk', constraint=models.UniqueConstraint(fields=('document','chunk_index'), name='unique_document_chunk')),
        migrations.AddConstraint(model_name='agentstep', constraint=models.UniqueConstraint(fields=('run','sequence_no'), name='unique_agent_step_sequence')),
    ]
