'use strict';
const TOOL_REGISTRY=Object.freeze({
  retrieve_internal_evidence:{risk:'internal_read',minimumRole:'viewer',requiresApproval:false,maxCallsPerRun:3,maxCostUsd:0,timeoutMs:8000},
  deep_web_research:{risk:'external_paid_read',minimumRole:'editor',requiresApproval:true,maxCallsPerRun:2,maxCostUsd:.25,timeoutMs:15000},
  evidence_synthesis:{risk:'local_compute',minimumRole:'viewer',requiresApproval:false,maxCallsPerRun:2,maxCostUsd:0,timeoutMs:10000},
  jira_create:{risk:'external_write',minimumRole:'admin',requiresApproval:true,blockedForResearchAgent:true,maxCallsPerRun:0,maxCostUsd:0,timeoutMs:15000}
});
const ROLE_RANK={viewer:0,reviewer:1,editor:2,admin:3,owner:4};
function evaluateToolPolicy({tool,role='viewer',initialRole=role,roleChanged=false,state='RUNNING',approved=false,calls=0,spentUsd=0}={}){const spec=TOOL_REGISTRY[tool];if(!spec)return{allowed:false,code:'AGENT_TOOL_UNKNOWN',reason:'Tool is not registered.'};if(['COMPLETED','FAILED','CANCELLED'].includes(state))return{allowed:false,code:'AGENT_RUN_TERMINAL',reason:'Terminal runs cannot invoke tools.'};if(roleChanged||role!==initialRole)return{allowed:false,code:'AGENT_ROLE_MUTATION_DETECTED',reason:'Role must be snapshotted when a run starts.'};if(spec.blockedForResearchAgent)return{allowed:false,code:'AGENT_TOOL_FORBIDDEN',reason:'This agent cannot perform external writes.'};if((ROLE_RANK[role]??-1)<(ROLE_RANK[spec.minimumRole]??99))return{allowed:false,code:'AGENT_ROLE_FORBIDDEN',reason:`${spec.minimumRole} role required.`};if(spec.requiresApproval&&!approved)return{allowed:false,code:'AGENT_APPROVAL_REQUIRED',reason:'Explicit approval is required before this tool can run.'};if(calls>=spec.maxCallsPerRun)return{allowed:false,code:'AGENT_TOOL_CALL_BUDGET_EXCEEDED',reason:'Per-run tool-call budget exhausted.'};if(spentUsd>=spec.maxCostUsd&&spec.maxCostUsd>0)return{allowed:false,code:'AGENT_COST_BUDGET_EXCEEDED',reason:'Per-run tool cost budget exhausted.'};return{allowed:true,tool,spec};}
module.exports={TOOL_REGISTRY,evaluateToolPolicy,ROLE_RANK};
