'use strict';
const {semanticSetScore,semanticSimilarity,groundingScore}=require('./semanticMetrics');
function mean(xs){const a=xs.filter(Number.isFinite);return a.length?a.reduce((s,x)=>s+x,0)/a.length:null}
function f1(p,r){return (p+r)>0?2*p*r/(p+r):0}
function macro(rows,key){return mean(rows.map(r=>Number(r[key])).filter(Number.isFinite))}
function bootstrapCI(values,stat=mean,B=2000,seed=42){const a=values.filter(Number.isFinite);if(!a.length)return null;let s=seed>>>0;const rand=()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296};const sims=[];for(let b=0;b<B;b++){const sample=[];for(let i=0;i<a.length;i++)sample.push(a[Math.floor(rand()*a.length)]);sims.push(stat(sample));}sims.sort((x,y)=>x-y);const q=p=>sims[Math.max(0,Math.min(sims.length-1,Math.floor(p*sims.length)))];return{estimate:stat(a),lower:q(.025),upper:q(.975),n:a.length,method:'bootstrap-percentile',B};}
function exactSetScore(gold,actual){const g=new Set((gold||[]).map(String)),a=new Set((actual||[]).map(String));let tp=0;for(const x of a)if(g.has(x))tp++;const precision=a.size?tp/a.size:0,recall=g.size?tp/g.size:1;return {precision,recall,f1:f1(precision,recall),tp,fp:Math.max(0,a.size-tp),fn:Math.max(0,g.size-tp)}}
function textSetScore(gold,actual,threshold=.45){return semanticSetScore(gold||[],actual||[],threshold)}
function claimGroundingScore(claims,evidence,threshold=.25){return groundingScore(claims,evidence,threshold)}
function scoreModule(gold,out,module){if(!gold||!out)return null;switch(module){case'assumptions':return textSetScore((gold.assumptions||[]).map(x=>x.text),(out.assumptions||[]).map(x=>x.text));case'challenge':return textSetScore((gold.challenges||[]).map(x=>x.question),(out.challenges||[]).map(x=>x.question));case'insights':return textSetScore((gold.insights||[]).map(x=>x.title),(out.insights||[]).map(x=>x.title));case'synthesize':return {recommendationMatch:gold.recommendation===out.recommendation?1:0,semanticSummary:semanticSimilarity(gold.summary||'',out.summary||'')};case'prd':return {scopeCoverage:textSetScore(gold.scope||[],out.scope||[]).recall};case'experiment':return {falsifiability:gold.falsifiable===true?(out.experiment?.successRule&&out.experiment?.failureRule?1:0):null};default:return null;}}
module.exports={mean,bootstrapCI,scoreModule,f1,macro,textSetScore,exactSetScore,claimGroundingScore};
