'use strict';
function normalizeTrace(t={}){return{requestId:String(t.requestId||''),workspaceId:String(t.workspaceId||''),decisionId:String(t.decisionId||''),module:String(t.module||''),model:String(t.model||''),modelVersion:String(t.modelVersion||t.model_version||''),promptVersion:String(t.promptVersion||t.prompt_version||''),retrieverVersion:String(t.retrieverVersion||t.retriever_version||''),tokensIn:Number(t.tokensIn||0),tokensOut:Number(t.tokensOut||0),latencyMs:Number(t.latencyMs||0),cost:Number(t.cost||0),validationStatus:t.validationStatus||'unknown',timestamp:t.timestamp||new Date().toISOString()}}
function aggregateTraces(traces=[]){const xs=traces.map(normalizeTrace);const lat=xs.map(x=>x.latencyMs).filter(Number.isFinite).sort((a,b)=>a-b);const percentile=p=>lat.length?lat[Math.min(lat.length-1,Math.floor((p/100)*(lat.length-1)))] : null;const percentileHigh=p=>lat.length?lat[Math.min(lat.length-1,Math.ceil((p/100)*lat.length)-1)] : null;return{requests:xs.length,totalCost:xs.reduce((a,x)=>a+x.cost,0),avgCost:xs.length?xs.reduce((a,x)=>a+x.cost,0)/xs.length:null,p50LatencyMs:percentile(50),p95LatencyMs:percentile(95),p99LatencyMs:percentileHigh(99),errorRate:xs.length?xs.filter(x=>!['pass','passed','ok'].includes(String(x.validationStatus).toLowerCase())).length/xs.length:null,validationPassRate:xs.length?xs.filter(x=>x.validationStatus==='pass'||x.validationStatus==='passed').length/xs.length:null,byModel:[...new Set(xs.map(x=>x.model).filter(Boolean))],
// byModelDetail: additive, mirrors the existing byModule breakdown shape.
// byModel (the plain name list above) is left exactly as-is so nothing that
// already reads it can break.
byModelDetail:[...new Set(xs.map(x=>x.model).filter(Boolean))].map(model=>{const ys=xs.filter(x=>x.model===model);return{model,requests:ys.length,cost:ys.reduce((a,x)=>a+x.cost,0),avgLatencyMs:ys.length?ys.reduce((a,x)=>a+x.latencyMs,0)/ys.length:null,errorRate:ys.length?ys.filter(x=>!['pass','passed','ok'].includes(String(x.validationStatus).toLowerCase())).length/ys.length:null}}),
byModule:[...new Set(xs.map(x=>x.module).filter(Boolean))].map(module=>{const ys=xs.filter(x=>x.module===module);return{module,requests:ys.length,cost:ys.reduce((a,x)=>a+x.cost,0),avgLatencyMs:ys.length?ys.reduce((a,x)=>a+x.latencyMs,0)/ys.length:null}})}}
module.exports={normalizeTrace,aggregateTraces};
