'use strict';
const crypto=require('node:crypto');
const VALID_RATER_STATES=['UNTRAINED','TRAINING','PILOT','QUALIFICATION_REVIEW','CERTIFIED','MAIN_STUDY','SUSPENDED'];
const VALID_STUDY_STATES=['DRAFT','REGISTERED','DATASET_FROZEN','CANDIDATES_FROZEN','PILOT','QUALIFICATION','MAIN_ANNOTATION','ADJUDICATION','GOLD_LOCKED','EVALUATION_COMPLETE','PUBLISHED'];
function hashJson(value){return crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');}
function makeStudy({id='HG-001',datasetVersion='TF-300-v4',rubricVersion='tf-rubric-v3.1',protocolVersion='HGT-1.1',candidateSnapshot='pending'}={}){
 return {id,version:'1.1',datasetVersion,rubricVersion,protocolVersion,candidateSnapshot,pilotCases:30,mainCases:300,developmentCases:60,validationCases:60,lockedTestCases:180,hiddenDuplicateRate:0.05,minimumIndependentRaters:2,primaryReliability:'weighted_cohen_kappa',secondaryReliability:['cohen_kappa','observed_agreement','intra_rater_consistency'],blindedComparison:true,adjudicationRequired:true,preserveRawRatings:true,claimLevelGroundTruth:true,status:'DRAFT',createdAt:new Date().toISOString()};
}
function isValidState(s){return VALID_RATER_STATES.includes(s)}
function canAnnotate(state){return ['PILOT','CERTIFIED','MAIN_STUDY'].includes(state)}
function transition(current,next){const allowed={UNTRAINED:['TRAINING'],TRAINING:['PILOT'],PILOT:['QUALIFICATION_REVIEW'],QUALIFICATION_REVIEW:['CERTIFIED','TRAINING'],CERTIFIED:['MAIN_STUDY','SUSPENDED'],MAIN_STUDY:['SUSPENDED'],SUSPENDED:['TRAINING']};if(!isValidState(current)||!isValidState(next)||!(allowed[current]||[]).includes(next)){const e=new Error(`Invalid rater state transition ${current} → ${next}`);e.code='INVALID_RATER_STATE_TRANSITION';throw e;}return next;}
function transitionStudy(current,next){const allowed={DRAFT:['REGISTERED'],REGISTERED:['DATASET_FROZEN'],DATASET_FROZEN:['CANDIDATES_FROZEN'],CANDIDATES_FROZEN:['PILOT'],PILOT:['QUALIFICATION'],QUALIFICATION:['MAIN_ANNOTATION'],MAIN_ANNOTATION:['ADJUDICATION'],ADJUDICATION:['GOLD_LOCKED'],GOLD_LOCKED:['EVALUATION_COMPLETE'],EVALUATION_COMPLETE:['PUBLISHED']};if(!VALID_STUDY_STATES.includes(current)||!VALID_STUDY_STATES.includes(next)||!(allowed[current]||[]).includes(next)){const e=new Error(`Invalid study transition ${current} → ${next}`);e.code='INVALID_STUDY_STATE_TRANSITION';throw e;}return next;}
function canAnnotateInStudy(raterState,studyStatus){return (raterState==='PILOT'&&studyStatus==='PILOT')||((raterState==='CERTIFIED'||raterState==='MAIN_STUDY')&&studyStatus==='MAIN_ANNOTATION')}
function requireFrozenStudy(study){if(!study||study.status!=='CANDIDATES_FROZEN') {const e=new Error('Study candidates must be frozen before annotation');e.code='CANDIDATES_NOT_FROZEN';throw e;}return true;}
function raterKey(studyId,raterId){return hashJson({studyId,raterId}).slice(0,24)}
function isLockedStatus(status){return ['DATASET_FROZEN','CANDIDATES_FROZEN','PILOT','QUALIFICATION','MAIN_ANNOTATION','ADJUDICATION','GOLD_LOCKED','EVALUATION_COMPLETE','PUBLISHED'].includes(status)}
function studyManifestHash(study){return hashJson({id:study.id,version:study.version,datasetVersion:study.datasetVersion,rubricVersion:study.rubricVersion,protocolVersion:study.protocolVersion,candidateSnapshot:study.candidateSnapshot,pilotCases:study.pilotCases,mainCases:study.mainCases,developmentCases:study.developmentCases,validationCases:study.validationCases,lockedTestCases:study.lockedTestCases,minimumIndependentRaters:study.minimumIndependentRaters,hiddenDuplicateRate:study.hiddenDuplicateRate})}
module.exports={VALID_RATER_STATES,VALID_STUDY_STATES,hashJson,makeStudy,isValidState,canAnnotate,canAnnotateInStudy,transition,transitionStudy,requireFrozenStudy,raterKey,isLockedStatus,studyManifestHash};
