'use strict';
function clamp(x,a=0,b=1){return Math.max(a,Math.min(b,x))}
function mean(xs){return xs?.length?xs.reduce((s,x)=>s+x,0)/xs.length:null}
function brierScore(rows){if(!rows?.length)return null;return mean(rows.map(r=>(clamp(Number(r.probability))-Number(r.outcome))**2))}
function expectedCalibrationError(rows,bins=10){if(!rows?.length)return null;let weighted=0;for(let i=0;i<bins;i++){const lo=i/bins,hi=(i+1)/bins,bucket=rows.filter(r=>Number(r.probability)>=lo&&(i===bins-1?Number(r.probability)<=hi:Number(r.probability)<hi));if(!bucket.length)continue;weighted+=bucket.length/rows.length*Math.abs(mean(bucket.map(r=>clamp(Number(r.probability))))-mean(bucket.map(r=>Number(r.outcome))))}return weighted}
function calibrationBuckets(rows,bins=10){return Array.from({length:bins},(_,i)=>{const lo=i/bins,hi=(i+1)/bins,b=(rows||[]).filter(r=>Number(r.probability)>=lo&&(i===bins-1?Number(r.probability)<=hi:Number(r.probability)<hi));return{bin:i,lower:lo,upper:hi,n:b.length,meanProbability:b.length?mean(b.map(r=>clamp(Number(r.probability)))):null,empiricalRate:b.length?mean(b.map(r=>Number(r.outcome))):null}})}
function rmse(rows){if(!rows?.length)return null;return Math.sqrt(mean(rows.map(r=>(Number(r.predicted)-Number(r.actual))**2)))}
function mae(rows){if(!rows?.length)return null;return mean(rows.map(r=>Math.abs(Number(r.predicted)-Number(r.actual))))}
function meanBias(rows){if(!rows?.length)return null;return mean(rows.map(r=>Number(r.predicted)-Number(r.actual)))}
function wilsonInterval(successes,n,z=1.96){if(!n)return null;const p=successes/n,den=1+z*z/n,center=(p+z*z/(2*n))/den,half=z*Math.sqrt((p*(1-p)+z*z/(4*n))/n)/den;return [Math.max(0,center-half),Math.min(1,center+half)]}
function twoProportionZ(x1,n1,x2,n2){if(!n1||!n2)return null;const p1=x1/n1,p2=x2/n2,p=(x1+x2)/(n1+n2),se=Math.sqrt(p*(1-p)*(1/n1+1/n2));return se?((p1-p2)/se):0}
function sampleSizeTwoProportion({baseline=0.1,mde=0.03,alpha=0.05,power=0.8}={}){if(!(baseline>0&&baseline<1&&mde>0&&alpha>0&&alpha<1&&power>0&&power<1))return null;const zAlpha=1.959964,zBeta=0.841621,p2=clamp(baseline+mde),pooled=2*baseline*(1-baseline),num=(zAlpha*Math.sqrt(pooled)+zBeta*Math.sqrt(baseline*(1-baseline)+p2*(1-p2)))**2;return Math.ceil(num/(mde*mde))}
function bootstrapCI(values,stat=mean,B=2000){const a=values.filter(Number.isFinite);if(!a.length)return null;let seed=42;const rnd=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};const sims=[];for(let b=0;b<B;b++){const sample=Array.from({length:a.length},()=>a[Math.floor(rnd()*a.length)]);sims.push(stat(sample))}sims.sort((a,b)=>a-b);const q=p=>sims[Math.floor((sims.length-1)*p)];return{estimate:stat(a),lower:q(.025),upper:q(.975),n:a.length,B}}
module.exports={clamp,mean,brierScore,expectedCalibrationError,calibrationBuckets,rmse,mae,meanBias,wilsonInterval,twoProportionZ,sampleSizeTwoProportion,bootstrapCI};
