'use strict';
const fs=require('node:fs'),path=require('node:path');
function cohenKappa(a,b,weighted=false,cats=[1,2,3,4,5]){const n=Math.min(a.length,b.length);if(!n)return null;let po=0;for(let i=0;i<n;i++){const w=weighted?1-Math.abs(a[i]-b[i])/(cats.length-1):(a[i]===b[i]?1:0);po+=w}po/=n;const pa=Object.fromEntries(cats.map(c=>[c,a.slice(0,n).filter(x=>x===c).length/n]));const pb=Object.fromEntries(cats.map(c=>[c,b.slice(0,n).filter(x=>x===c).length/n]));let pe=0;for(const c of cats)for(const d of cats){const w=weighted?1-Math.abs(c-d)/(cats.length-1):(c===d?1:0);pe+=w*(pa[c]||0)*(pb[d]||0)}return pe===1?1:(po-pe)/(1-pe)}
function matrix(a,b){const out={};for(let i=0;i<Math.min(a.length,b.length);i++){const k=`${a[i]}->${b[i]}`;out[k]=(out[k]||0)+1}return out}
function main(){const input=process.argv[2]||path.join(__dirname,'..','eval','annotation_export.json');if(!fs.existsSync(input)){console.error('Missing annotation export:',input);process.exit(2)}const rows=JSON.parse(fs.readFileSync(input,'utf8'));const adjudPath=process.argv.find(x=>x.startsWith('--adjudications='))?.split('=')[1];const adjud=adjudPath&&fs.existsSync(adjudPath)?JSON.parse(fs.readFileSync(adjudPath,'utf8')):{};const by=new Map();for(const r of rows){if(!r.case_id||!r.dimension)continue;const k=`${r.case_id}:${r.dimension}`;(by.get(k)||by.set(k,[]).get(k)).push({rater_id:r.rater_id||r.rater,score:Number(r.score)})}
const gold=[];let pairCount=0,exact=0;const perDim={};
for(const [k,arr] of by){const [case_id,dimension]=k.split(':');const byRater=new Map();for(const x of arr)if(Number.isFinite(x.score)&&x.rater_id&&!byRater.has(x.rater_id))byRater.set(x.rater_id,x.score);const vals=[...byRater.entries()];let status='pending',score=null;if(vals.length>=2){pairCount++;const a=vals[0][1],b=vals[1][1];const same=a===b;if(same)exact++;const adj=adjud[`${k}`];if(same){status='agreement';score=a}else if(adj!==undefined){status='adjudicated';score=Number(typeof adj==='object'?adj.final_score:adj)}}const g={case_id,dimension,score,status,rater_count:vals.length,agreement:status==='agreement',adjudicated:status==='adjudicated',ratings:vals.map(([rater_id,s])=>({rater_id,score:s}))};gold.push(g);const mod=(arr[0]?.module)||'unknown';const d=perDim[mod]||{a:[],b:[],matrix:{}};if(vals.length>=2){d.a.push(vals[0][1]);d.b.push(vals[1][1]);d.matrix=matrix(d.a,d.b)}perDim[mod]=d}
const reliability={};for(const [mod,x] of Object.entries(perDim))reliability[mod]={pairs:x.a.length,exactAgreementRate:x.a.length?x.a.filter((v,i)=>v===x.b[i]).length/x.a.length:0,cohenKappa:cohenKappa(x.a,x.b,false),weightedKappa:cohenKappa(x.a,x.b,true),disagreementMatrix:x.matrix};
const duplicateByRater=new Map();for(const r of rows.filter(x=>x.is_hidden_duplicate)){const key=r.rater_id||r.rater;(duplicateByRater.get(key)||duplicateByRater.set(key,[]).get(key)).push(r)}let hiddenPairs=0,hiddenAgreement=0;for(const arr of duplicateByRater.values()){const base=new Map();const dups=[];for(const r of arr){const key=`${r.source_case_id||r.case_id}:${r.module}`;(base.get(key)||base.set(key,[]).get(key)).push(r)}for(const [key,rs] of base){for(const r of rs){if(!r.scores)continue;const nonDup=rows.find(x=>x.rater_id===r.rater_id&&!x.is_hidden_duplicate&&`${x.case_id}:${x.module}`===key);if(nonDup){for(const dim of Object.keys(r.scores)){if(nonDup.scores?.[dim]!==undefined){hiddenPairs++;if(Number(nonDup.scores[dim])===Number(r.scores[dim]))hiddenAgreement++}}}}}}
const summary={annotations:rows.length,dimensionPairs:pairCount,exactAgreementRate:pairCount?exact/pairCount:0,reliabilityByModule:reliability,hiddenDuplicate:{pairs:hiddenPairs,exactConsistencyRate:hiddenPairs?hiddenAgreement/hiddenPairs:0},goldReadyDimensions:gold.filter(g=>g.status==='agreement'||g.status==='adjudicated').length,goldReady:Boolean(gold.length&&gold.every(g=>g.status==='agreement'||g.status==='adjudicated'))};
console.log(JSON.stringify({summary,gold},null,2));}
main();
