'use strict';
const {requireUser,requireOrganizationRole,requestId}=require('../lib/auth');
const {limit}=require('../lib/rateLimit');
const {applySecurityHeaders,bodySizeOk}=require('../lib/security');
const {rest}=require('../lib/db');
const {createPlan,runResearchAgent}=require('../lib/agentOrchestrator');
const crypto=require('node:crypto');
const digest=value=>crypto.createHash('sha256').update(JSON.stringify(value??null)).digest('hex');
async function persistRun(result,{organizationId,userId,requestId}){const base={id:result.runId,organization_id:organizationId,user_id:userId,request_id:requestId,status:result.status,agent_version:result.plan.agentVersion,goal:result.plan.goal,trace:result.trace,metrics:result.metrics};const saved=await rest('thinkforge_agent_runs','POST',base);if(!saved.ok)throw new Error('Could not persist agent run');const steps=(result.trace||[]).map((entry,sequence_no)=>({run_id:result.runId,organization_id:organizationId,sequence_no,state:entry.state||result.status,event_type:entry.type,detail:entry}));if(steps.length){const r=await rest('thinkforge_agent_steps','POST',steps);if(!r.ok)throw new Error('Could not persist agent trace steps');}const calls=(result.trace||[]).filter(x=>x.type==='TOOL_COMPLETED'||x.type==='TOOL_STARTED').map(x=>({run_id:result.runId,organization_id:organizationId,tool_name:x.tool,status:x.type==='TOOL_COMPLETED'?'completed':'started',input_hash:digest({tool:x.tool,runId:result.runId}),output_hash:x.type==='TOOL_COMPLETED'?digest(x):null,latency_ms:0,cost_usd:0,error_code:null}));if(calls.length){const r=await rest('thinkforge_agent_tool_calls','POST',calls);if(!r.ok)throw new Error('Could not persist agent tool calls');}}
module.exports=async function(req,res){applySecurityHeaders(res);const rid=requestId(req);res.setHeader('x-request-id',rid);if(req.method!=='POST')return res.status(405).json({error:'Method not allowed',requestId:rid});if(!bodySizeOk(req))return res.status(413).json({error:'Body too large',requestId:rid});const user=await requireUser(req,res);if(!user)return;const limited=await limit(req,{scope:'agent',max:10,windowMs:60000});if(!limited.ok)return res.status(429).json({error:'Rate limited',requestId:rid});const body=req.body||{},organizationId=String(body.organizationId||'').trim();if(!organizationId)return res.status(400).json({error:'organizationId required',code:'ORGANIZATION_REQUIRED',requestId:rid});try{await requireOrganizationRole(user.id,organizationId,body.action==='feedback'?'viewer':'editor');}catch(e){return res.status(e.status||403).json({error:e.message||'Organization membership required',code:e.code||'FORBIDDEN',requestId:rid});}try{if(body.action==='plan')return res.status(200).json({result:createPlan(body.input||{}),requestId:rid});if(body.action==='feedback'){const runId=String(body.runId||'').trim(),outcome=String(body.outcome||'');if(!runId||!['accepted','rejected','edited','inconclusive'].includes(outcome))return res.status(400).json({error:'runId and valid outcome required',code:'INVALID_FEEDBACK',requestId:rid});const run=await rest(`thinkforge_agent_runs?id=eq.${encodeURIComponent(runId)}&organization_id=eq.${encodeURIComponent(organizationId)}&select=id`,'GET');const rows=run.ok?await run.json():[];if(!rows?.length)return res.status(404).json({error:'Agent run not found in this organization',code:'AGENT_RUN_NOT_FOUND',requestId:rid});const r=await rest('thinkforge_agent_feedback','POST',{run_id:runId,organization_id:organizationId,user_id:user.id,rating:body.rating==null?null:Number(body.rating),outcome,note:String(body.note||'').slice(0,2000)});if(!r.ok)throw new Error('Could not save feedback');return res.status(200).json({ok:true,requestId:rid});}if(body.action!=='run')return res.status(400).json({error:'action must be plan, run, or feedback',code:'INVALID_AGENT_ACTION',requestId:rid});const result=await runResearchAgent({...body.input,approved:body.approved===true},{role:'editor'});try{await persistRun(result,{organizationId,userId:user.id,requestId:rid});}catch(e){return res.status(503).json({error:e.message,code:'AGENT_TRACE_PERSIST_FAILED',requestId:rid});}return res.status(result.status==='FAILED'?502:200).json({result,requestId:rid});}catch(e){return res.status(e.status||400).json({error:e.message||'Agent request failed',code:e.code||'AGENT_REQUEST_FAILED',requestId:rid});}};
