'use strict';
const fs=require('node:fs'),path=require('node:path');
const {requireUser,requestId}=require('../lib/auth');
const {limit}=require('../lib/rateLimit');const {applySecurityHeaders,bodySizeOk,hash}=require('../lib/security');const {rest}=require('../lib/db');const {callModel}=require('../lib/ai');
const {buildAssignments}=require('../lib/annotationAssignments');
const {canAnnotateInStudy}=require('../lib/researchStudy');
const dataset=JSON.parse(fs.readFileSync(path.join(__dirname,'..','eval','benchmark_300.json'),'utf8'));
const rubrics=JSON.parse(fs.readFileSync(path.join(__dirname,'..','eval','rubrics.json'),'utf8'));
async function getStudyRow(){try{const r=await rest('thinkforge_research_studies?id=eq.HG-001&select=id,version,dataset_version,rubric_version,protocol_version,status','GET');if(!r.ok)return null;const rows=await r.json();return rows?.[0]||null}catch{return null}}
function validScores(module,scores){const dims=rubrics.dimensions[module]||[];if(!scores||typeof scores!=='object')return ['scores_required'];for(const d of dims){if(!Number.isFinite(Number(scores[d]))||Number(scores[d])<1||Number(scores[d])>5)return [`invalid_score:${d}`]}return []}
function assignmentFor(cases,userId,presentationId){return buildAssignments(cases,userId).find(x=>x.presentationId===presentationId)||null}
async function requireCertifiedRater(userId){try{const r=await rest(`thinkforge_evaluation_rater_profiles?rater_id=eq.${encodeURIComponent(userId)}&study_id=eq.HG-001&select=qualification_status,pilot_completed,pilot_quality,hidden_duplicate_consistency,attention_check_rate`,'GET');if(!r.ok)return null;const rows=await r.json();return rows?.[0]||null}catch{return null}}
async function duplicate(userId,presentationId){const r=await rest(`thinkforge_evaluation_annotations?rater_id=eq.${encodeURIComponent(userId)}&presentation_id=eq.${encodeURIComponent(presentationId)}&select=id`,'GET');if(!r.ok)return false;return (await r.json()).length>0}
async function getCandidate(caseId,c,rid){
 const existing=await rest(`thinkforge_evaluation_candidates_v2?study_id=eq.HG-001&case_id=eq.${encodeURIComponent(caseId)}&select=case_id,module,model,prompt_version,retriever_version,output_json,request_id,generated_at,checksum&study_id=eq.HG-001`,'GET');
 if(existing.ok){const rows=await existing.json();if(rows?.[0])return rows[0]}
 if(process.env.NODE_ENV==='production' || process.env.ALLOW_LAZY_CANDIDATES!=='true'){const e=new Error('Candidate snapshot is not frozen for this study');e.code='CANDIDATE_NOT_FROZEN';throw e;}
 const out=await callModel(c.module,c.decision,`candidate:${caseId}:${rid}`);const row={study_id:'HG-001',case_id:caseId,module:c.module,model:out.meta.model,prompt_version:out.meta.promptVersion,retriever_version:out.meta.retrieverVersion,output_json:out.data,request_id:out.meta.requestId,generated_at:new Date().toISOString(),checksum:hash(out.data)};const ins=await rest('thinkforge_evaluation_candidates_v2','POST',row);if(ins.ok){const created=await ins.json();return created?.[0]||row}return row}
module.exports=async function handler(req,res){applySecurityHeaders(res);const rid=requestId(req);res.setHeader('x-request-id',rid);if(req.method!=='POST')return res.status(405).json({error:'Method not allowed',requestId:rid});if(!bodySizeOk(req))return res.status(413).json({error:'Body too large',code:'BODY_TOO_LARGE',requestId:rid});const user=await requireUser(req,res);if(!user)return;const rl=await limit(req,{scope:'annotations',max:60,windowMs:60000});if(!rl.ok)return res.status(429).json({error:'Rate limit exceeded',code:'RATE_LIMITED',requestId:rid});const b=req.body||{};
const rater=await requireCertifiedRater(user.id);
const study=await getStudyRow();
if(b.action==='get'||b.action==='submit'){const validPhase=canAnnotateInStudy(rater?.qualification_status||'UNTRAINED',study?.status||'DRAFT');if(!validPhase)return res.status(403).json({error:'Rater/study phase does not permit annotation',code:'ANNOTATION_PHASE_LOCKED',raterState:rater?.qualification_status||'UNTRAINED',studyStatus:study?.status||'DRAFT',requestId:rid});}
if(b.action==='list'){const asn=buildAssignments(dataset.cases,user.id);return res.status(200).json({datasetVersion:dataset.version,assignmentVersion:'tf-human-v4',cases:asn.map(a=>{const c=dataset.cases.find(x=>x.id===a.caseId);return {id:c.id,presentationId:a.presentationId,module:c.module,difficulty:c.difficulty,domain:c.domain,annotation_status:c.annotation_status,dimensions:rubrics.dimensions[c.module]||[]}}),requestId:rid})}
if(b.action==='get'){const a=assignmentFor(dataset.cases,user.id,b.presentationId);if(!a||a.caseId!==b.caseId)return res.status(400).json({error:'Invalid annotation presentation',code:'INVALID_PRESENTATION',requestId:rid});const c=dataset.cases.find(x=>x.id===a.sourceCaseId);if(!c)return res.status(404).json({error:'Case not found',requestId:rid});try{const candidate=await getCandidate(c.id,c,rid);return res.status(200).json({case:{id:c.id,module:c.module,difficulty:c.difficulty,domain:c.domain,decision:c.decision,input_prompt:c.input_prompt},rubric:{version:rubrics.version,scale:rubrics.scale,dimensions:rubrics.dimensions[c.module],anchors:Object.fromEntries(rubrics.dimensions[c.module].map(d=>[d,rubrics.dimension_anchors?.[d]||{}]))},candidate:{output:candidate.output_json,model:candidate.model,promptVersion:candidate.prompt_version,retrieverVersion:candidate.retriever_version,checksum:candidate.checksum,frozen:Boolean(candidate.checksum),studyVersion:study?.version||null,protocolVersion:study?.protocol_version||null},requestId:rid})}catch(e){return res.status(502).json({error:e.message||'Candidate generation failed',code:e.code||'CANDIDATE_FAILED',requestId:rid})}}
if(b.action==='submit'){const a=assignmentFor(dataset.cases,user.id,b.presentationId);if(!a||a.caseId!==b.caseId)return res.status(400).json({error:'Invalid annotation presentation',code:'INVALID_PRESENTATION',requestId:rid});const c=dataset.cases.find(x=>x.id===a.sourceCaseId);if(!c)return res.status(404).json({error:'Case not found',requestId:rid});const errors=validScores(c.module,b.scores);if(errors.length)return res.status(400).json({error:'Invalid annotation',code:'INVALID_ANNOTATION',details:errors,requestId:rid});if(await duplicate(user.id,b.presentationId))return res.status(409).json({error:'You already submitted this presentation',code:'DUPLICATE_ANNOTATION',requestId:rid});try{const candidate=await getCandidate(c.id,c,rid);if(!candidate?.checksum) {const e=new Error('Frozen candidate checksum unavailable');e.code='CANDIDATE_CHECKSUM_MISSING';throw e;}const allowedLabels=new Set(['SUPPORTED','PARTIALLY_SUPPORTED','UNSUPPORTED','CONTRADICTED','NOT_VERIFIABLE']);const claimLabels=Array.isArray(b.claimLabels)?b.claimLabels.filter(x=>x&&allowedLabels.has(x.label)&&Array.isArray(x.evidenceIds||[])).slice(0,100).map(x=>({claimId:String(x.claimId||''),label:x.label,evidenceIds:(x.evidenceIds||[]).map(String).slice(0,20),note:String(x.note||'').slice(0,1000)})):[];const confidence=Math.max(1,Math.min(5,Number(b.confidence||3)));const unsupportedClaimSeverity=Number.isFinite(Number(b.unsupportedClaimSeverity))?Math.max(0,Math.min(2,Number(b.unsupportedClaimSeverity))):null;const citationCorrectness=Number.isFinite(Number(b.citationCorrectness))?Math.max(0,Math.min(2,Number(b.citationCorrectness))):null;const r=await rest('thinkforge_evaluation_annotations','POST',{study_id:'HG-001',case_id:c.id,presentation_id:b.presentationId,rater_id:user.id,module:c.module,scores:b.scores,claim_labels:claimLabels,confidence,unsupported_claim_severity:unsupportedClaimSeverity,citation_correctness:citationCorrectness,notes:String(b.notes||'').slice(0,5000),rubric_version:rubrics.version,is_hidden_duplicate:Boolean(a.isHiddenDuplicate),source_case_id:a.sourceCaseId,candidate_frozen:true,study_version:study?.version||null,protocol_version:study?.protocol_version||null,candidate_checksum:candidate.checksum||null,created_at:new Date().toISOString()});if(!r.ok)throw new Error(await r.text());return res.status(201).json({ok:true,caseId:c.id,requestId:rid});}catch(e){return res.status(502).json({error:e.message||'Annotation save failed',code:'ANNOTATION_SAVE_FAILED',requestId:rid});}}
if(b.action==='metrics'){try{const r=await rest('thinkforge_evaluation_annotations?select=case_id,presentation_id,source_case_id,is_hidden_duplicate,rater_id,module,scores,created_at&order=created_at.asc','GET');if(!r.ok)throw new Error(await r.text());const rows=await r.json();const groups=new Map();for(const x of rows){for(const [dim,score] of Object.entries(x.scores||{})){const k=`${x.case_id}:${x.module}:${dim}`;(groups.get(k)||groups.set(k,[]).get(k)).push({rater_id:x.rater_id,score:Number(score)})}}const cats=[1,2,3,4,5];const kapp=(a,b,weighted=false)=>{const n=Math.min(a.length,b.length);if(!n)return null;let po=0;for(let i=0;i<n;i++){const d=Math.abs(a[i]-b[i])/(cats.length-1);po+=weighted?1-d:(a[i]===b[i]?1:0)}po/=n;const pa=Object.fromEntries(cats.map(c=>[c,a.slice(0,n).filter(x=>x===c).length/n]));const pb=Object.fromEntries(cats.map(c=>[c,b.slice(0,n).filter(x=>x===c).length/n]));let pe=0;for(const c of cats){for(const d of cats){const w=weighted?1-Math.abs(c-d)/(cats.length-1):(c===d?1:0);pe+=w*(pa[c]||0)*(pb[d]||0)}}return pe===1?1:(po-pe)/(1-pe)};let pairs=0,agree=0;const kd={};const disagreement={};for(const [k,v] of groups){const byRater=new Map();for(const item of v)if(!byRater.has(item.rater_id))byRater.set(item.rater_id,item.score);const vals=[...byRater.values()];const dim=k.split(':')[2],mod=k.split(':')[1];if(vals.length>=2){pairs++;if(vals[0]===vals[1])agree++;(kd[mod]??=[]).push(vals);const matrix=disagreement[`${mod}:${dim}`]??{};const key=`${vals[0]}->${vals[1]}`;matrix[key]=(matrix[key]||0)+1;disagreement[`${mod}:${dim}`]=matrix}}const kappaByModule={};for(const [mod,arr] of Object.entries(kd)){const a=arr.map(x=>x[0]),bb=arr.map(x=>x[1]);kappaByModule[mod]={cohen:kapp(a,bb,false),weighted:kapp(a,bb,true)}}const dupRows=rows.filter(x=>x.is_hidden_duplicate);const dupByRater={};for(const x of dupRows){(dupByRater[x.rater_id]??=[]).push(x)}let dupPairs=0,dupAgree=0;for(const arr of Object.values(dupByRater)){const map=new Map();for(const x of arr){const oldKey=`${x.source_case_id}:${x.module}`;const prev=map.get(oldKey);if(prev){for(const [d,s] of Object.entries(x.scores||{})){if(prev.scores&&prev.scores[d]!==undefined){dupPairs++;if(Number(prev.scores[d])===Number(s))dupAgree++;}}}map.set(oldKey,x)}}return res.status(200).json({annotations:rows.length,dimensionPairs:pairs,exactAgreementRate:pairs?agree/pairs:0,kappaByModule,disagreementMatrices:disagreement,hiddenDuplicate:{pairs:dupPairs,exactConsistencyRate:dupPairs?dupAgree/dupPairs:0},advisoryGoldReadyDimensions:[...groups.values()].filter(v=>{const u=new Set(v.map(x=>x.rater_id));return u.size>=2&&new Set(v.filter(x=>x.score).map(x=>x.score)).size===1}).length,requestId:rid});}catch(e){return res.status(502).json({error:e.message||'Metrics failed',code:'ANNOTATION_METRICS_FAILED',requestId:rid})}}
return res.status(400).json({error:'Unsupported annotation action',code:'INVALID_ACTION',requestId:rid});};
