'use strict';
const crypto=require('node:crypto');
const {requireUser,requireOrganizationRole,requestId}=require('../lib/auth');
const {limit}=require('../lib/rateLimit');
const {applySecurityHeaders,bodySizeOk}=require('../lib/security');
const {analyzeDiscovery,analyzeDiscoverySemantically,buildDeepResearchReport,discoveryResearchPlan,humanResearchEvidence}=require('../lib/productDiscovery');
const {callModel}=require('../lib/ai');
const {recordInteraction}=require('../lib/aiTelemetry');
const {validateReasoningOutput,verifyClaims,buildReasoningContext}=require('../lib/reasoning');
const {saveDiscovery}=require('../lib/domainRepository');
const {validateSemanticDiscovery}=require('../lib/discoveryContracts');
const {validateCanonicalGraph}=require('../lib/domainModel');
const {runDeepWebSweep}=require('../lib/deepResearchWeb');
module.exports=async function(req,res){applySecurityHeaders(res);const rid=requestId(req);res.setHeader('x-request-id',rid);if(req.method!=='POST')return res.status(405).json({error:'Method not allowed',requestId:rid});if(!bodySizeOk(req))return res.status(413).json({error:'Body too large',requestId:rid});const user=await requireUser(req,res);if(!user)return;const rl=await limit(req,{scope:'discovery',max:60,windowMs:60000});if(!rl.ok)return res.status(429).json({error:'Rate limited',requestId:rid});const b=req.body||{};try{if(b.action==='deep_research_plan'){const bundle=b.bundle||{};return res.status(200).json({plan:discoveryResearchPlan({question:bundle.researchQuestion,questionType:bundle.questionType,decisionImpact:bundle.decisionImpact||'medium',segments:bundle.segments,desiredOutcome:bundle.desiredOutcome}),requestId:rid});}if(b.action==='deep_research'){
  // deep_research can fan out to up to 24 paid third-party (Tavily) searches per call.
  // The general 60/min 'discovery' scope above is shared with cheap actions (analyze/reason/save),
  // so it alone doesn't bound spend on this one. Require org membership at editor+ and give this
  // action its own tight budget on top of the shared one.
  const drOrgId=String(b.organizationId||'').trim();
  if(!drOrgId)return res.status(400).json({error:'organizationId required for deep research',code:'ORGANIZATION_REQUIRED',requestId:rid});
  try{await requireOrganizationRole(user.id,drOrgId,'editor');}catch(e){return res.status(e.status||403).json({error:e.message||'Editor role required for deep research',code:e.code||'FORBIDDEN',requestId:rid});}
  const drLimit=await limit(req,{scope:'discovery-deep-research',max:5,windowMs:60000});
  if(!drLimit.ok)return res.status(429).json({error:'Rate limit exceeded',code:'RATE_LIMITED',requestId:rid});
  let bundle={...(b.bundle||{})};if(!Array.isArray(bundle.webSources)&&!Array.isArray(bundle.sources)){const sweep=await runDeepWebSweep(bundle);if(sweep.errors?.length&&sweep.retained.length===0)throw Object.assign(new Error('Deep research web sweep failed for all queries'),{code:'DEEP_RESEARCH_SWEEP_FAILED',status:502,details:sweep.errors});bundle.webSources=sweep.retained;bundle.deepResearchSweep=sweep;}const report=buildDeepResearchReport(bundle);await recordInteraction({userId:user.id,decisionId:bundle.decision?.id,requestId:rid,module:'discovery_deep_research',meta:{provider:report.sourceAudit?.provider||'tavily',status:report.status,independentSources:report.quality.sources.independent},validationStatus:'passed',output:{status:report.status,quality:report.quality,saturation:report.saturation}});return res.status(200).json({result:report,requestId:rid});}if(b.action==='human_evidence_preview'){return res.status(200).json({result:humanResearchEvidence(b.items||[]),requestId:rid});}if(b.action==='analyze'){const bundle=b.bundle||{};if(b.mode==='heuristic')return res.status(200).json({result:analyzeDiscovery(bundle),meta:{mode:'heuristic',verified:false},requestId:rid});if(!process.env.AI_API_KEY)return res.status(503).json({error:'Semantic discovery requires AI_API_KEY; use mode=heuristic only for offline development.',code:'SEMANTIC_AI_REQUIRED',requestId:rid});const out=await analyzeDiscoverySemantically(bundle,{callSemanticModel:async context=>{const modelInput={title:bundle.title,problem:bundle.problem,user:bundle.user,context:bundle.context,desiredOutcome:context.desiredOutcome,researchQuestion:context.researchQuestion,evidence:context.evidence,assumptions:bundle.assumptions||[],opportunities:bundle.opportunities||[],alternatives:bundle.alternatives||[],decision:bundle.decision||null};const ai=await callModel('discovery_semantic',modelInput,rid);return {...ai.data,model:ai.meta.model,promptVersion:ai.meta.promptVersion,meta:ai.meta};}});await recordInteraction({userId:user.id,decisionId:bundle.decision?.id,requestId:rid,module:'discovery_semantic',meta:out.semantic||{},validationStatus:'passed',output:out});return res.status(200).json({result:out,meta:out.semantic,requestId:rid});}
if(b.action==='reason'){const bundle=b.bundle||{};const ctx=buildReasoningContext(bundle);const decision={...bundle.decision,evidence:ctx.evidence,assumptions:ctx.assumptions,opportunities:ctx.opportunities,desiredOutcome:ctx.desiredOutcome,claims:ctx.claims,candidateEvidence:ctx.candidateEvidence};const out=await callModel('reasoning',decision,rid);const issues=validateReasoningOutput(out.data,ctx.evidence);if(issues.length)throw Object.assign(new Error(`Reasoning validation failed: ${issues.join('; ')}`),{code:'AI_REASONING_INVALID',status:422});const verified=verifyClaims(out.data.claims,ctx.evidence);await recordInteraction({userId:user.id,decisionId:bundle.decision?.id,requestId:rid,module:'reasoning',meta:out.meta,validationStatus:'passed',output:{...out.data,claims:verified}});return res.status(200).json({result:{...out.data,claims:verified},meta:out.meta,requestId:rid});}if(b.action==='save'){const id=b.record?.id||crypto.randomUUID();const organizationId=b.organizationId||null;const record=b.record||{};const evidenceIds=(record.evidence||[]).map(e=>e?.id).filter(Boolean);if(record.semantic&&record.semantic.mode==='llm_verified'){const checked=validateSemanticDiscovery(record.semantic,{evidenceIds});if(!checked.success)return res.status(422).json({error:'Discovery semantic record failed validation',code:'DISCOVERY_RECORD_CONTRACT_INVALID',issues:checked.error.issues,requestId:rid});}if(!record.desiredOutcome||!record.researchQuestion)return res.status(422).json({error:'Discovery save requires desiredOutcome and researchQuestion',code:'DISCOVERY_RECORD_INCOMPLETE',requestId:rid});if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)return res.status(200).json({ok:true,id,localOnly:true,requestId:rid});const out=await saveDiscovery({userId:user.id,organizationId,record:{...record,id},requestId:rid});return res.status(200).json({ok:true,id,...(out||{}),requestId:rid});}return res.status(400).json({error:'Unsupported discovery action',requestId:rid});}catch(e){return res.status(e.status||400).json({error:e.message||'Discovery operation failed',code:e.code||'DISCOVERY_FAILED',requestId:rid});}};
