'use strict';
const crypto=require('node:crypto');
const {requireUser,requestId}=require('../lib/auth');const {limit}=require('../lib/rateLimit');const {applySecurityHeaders,bodySizeOk}=require('../lib/security');const {rest}=require('../lib/db');
const {fetchWithResilience}=require('../lib/http');
function basicAuth(email,token){return Buffer.from(`${email}:${token}`).toString('base64');}
function toADF(text){return {type:'doc',version:1,content:String(text||'').slice(0,12000).split('\n').map(t=>({type:'paragraph',content:t?[{type:'text',text:t}]:[]}))};}
module.exports=async function handler(req,res){applySecurityHeaders(res);const rid=requestId(req);res.setHeader('x-request-id',rid);if(req.method!=='POST')return res.status(405).json({error:'Method not allowed',requestId:rid});if(!bodySizeOk(req))return res.status(413).json({error:'Request body too large',code:'BODY_TOO_LARGE',requestId:rid});const rl=await limit(req,{scope:'jira',max:10,windowMs:60000});if(!rl.ok)return res.status(429).json({error:'Rate limit exceeded',code:'RATE_LIMITED',requestId:rid});const user=await requireUser(req,res);if(!user)return;
const {decision,confirm}=req.body||{};if(confirm!==true)return res.status(400).json({error:'Explicit confirmation required before creating Jira work',code:'CONFIRMATION_REQUIRED',requestId:rid});if(!decision?.title)return res.status(400).json({error:'Decision is required',code:'INVALID_REQUEST',requestId:rid});
const idem=String(req.headers?.['idempotency-key']||'').slice(0,200);if(!idem)return res.status(400).json({error:'Idempotency-Key required for external writes',code:'IDEMPOTENCY_REQUIRED',requestId:rid});
const base=(process.env.JIRA_BASE_URL||'').replace(/\/$/,'');const email=process.env.JIRA_EMAIL;const token=process.env.JIRA_API_TOKEN;const projectKey=process.env.JIRA_PROJECT_KEY;if(!base||!email||!token||!projectKey)return res.status(503).json({error:'Jira server integration is not configured',code:'JIRA_NOT_CONFIGURED',requestId:rid});
try{const existing=await rest(`thinkforge_external_actions?user_id=eq.${encodeURIComponent(user.id)}&idempotency_key=eq.${encodeURIComponent(idem)}`,'GET',undefined,'return=representation');if(existing.ok){const j=await existing.json();if(j?.[0]?.response_json)return res.status(200).json({...j[0].response_json,replayed:true,requestId:rid});}}
catch{}
const headers={'Content-Type':'application/json',Authorization:`Basic ${basicAuth(email,token)}`,'X-ThinkForge-Request-Id':rid};
async function createIssue(summary,description,issueType,parent){const payload={fields:{project:{key:projectKey},summary:String(summary).slice(0,250),description:toADF(description),issuetype:{name:issueType}}};if(parent)payload.fields.parent={key:parent};const r=await fetchWithResilience(`${base}/rest/api/3/issue`,{method:'POST',headers,body:JSON.stringify(payload)},{provider:'jira',timeoutMs:Number(process.env.JIRA_TIMEOUT_MS||15000)});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j?.errorMessages?.join('; ')||JSON.stringify(j?.errors||j));return j;}
try{const epic=await createIssue(decision.title,decision.artifacts?.prd||decision.prd||decision.problem,'Epic');const out={issues:[{key:epic.key,id:epic.id,type:'Epic',summary:decision.title}],actor:user.id,requestId:rid};for(const [summary,desc] of [['Validate critical assumptions',(decision.assumptions||[]).map(a=>`- ${a.text}`).join('\n')||'Review assumptions'],['Run experiment',`Hypothesis: ${decision.experiment?.hypothesis||'Define hypothesis'}\nPrimary metric: ${decision.experiment?.primary||'Define metric'}`],['Measure outcome','Record actual result and compare it with prediction.']]){try{const x=await createIssue(summary,desc,'Task',epic.key);out.issues.push({key:x.key,id:x.id,type:'Task',summary});}catch(e){out.issues.push({type:'Task',summary,error:e.message});}}
try{await rest('thinkforge_external_actions','POST',{user_id:user.id,action_type:'jira_create',idempotency_key:idem,request_id:rid,response_json:out});}catch{}return res.status(200).json(out);
}catch(e){return res.status(502).json({error:e.message||'Jira integration failed',code:'JIRA_WRITE_FAILED',requestId:rid});}}
