'use strict';
const fs=require('node:fs'),path=require('node:path');
const {requireUser,requestId}=require('../lib/auth');
const {limit}=require('../lib/rateLimit');
const {applySecurityHeaders,bodySizeOk}=require('../lib/security');
const {rest}=require('../lib/db');
const {makeStudy,transitionStudy,VALID_STUDY_STATES}=require('../lib/researchStudy');
const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'..','eval','study_manifest.json'),'utf8'));
function esc(v){return encodeURIComponent(String(v));}
function canManageResearch(user,study){const admins=(process.env.RESEARCH_ADMIN_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);return Boolean(user?.id&&(admins.includes(user.id)||!study?.created_by||study.created_by===user.id));}
async function getStudy(studyId){const r=await rest(`thinkforge_research_studies?study_id=eq.${esc(studyId)}&select=*`,'GET');if(!r.ok)return null;const rows=await r.json();return rows?.[0]||null;}
module.exports=async function(req,res){applySecurityHeaders(res);const rid=requestId(req);res.setHeader('x-request-id',rid);if(req.method!=='POST')return res.status(405).json({error:'Method not allowed',requestId:rid});if(!bodySizeOk(req))return res.status(413).json({error:'Body too large',requestId:rid});const user=await requireUser(req,res);if(!user)return;const rl=await limit(req,{scope:'research',max:60,windowMs:60000});if(!rl.ok)return res.status(429).json({error:'Rate limited',requestId:rid});const b=req.body||{};const studyId=String(b.studyId||manifest.study_id);
try{
 if(b.action==='manifest')return res.status(200).json({manifest,requestId:rid});
 if(b.action==='status'){const row=await getStudy(studyId);return res.status(200).json({study:row||makeStudy({id:studyId,datasetVersion:manifest.dataset_version,rubricVersion:manifest.rubric_version,protocolVersion:manifest.protocol_version}),requestId:rid});}
 if(b.action==='transition'){const row=await getStudy(studyId);if(row&&!canManageResearch(user,row))return res.status(403).json({error:'Research study transition requires study owner or configured research admin',code:'RESEARCH_ADMIN_REQUIRED',requestId:rid});const current=row?.status||'DRAFT';const next=transitionStudy(current,String(b.nextState));const now=new Date().toISOString();const payload={study_id:studyId,study_version:manifest.study_version,dataset_version:manifest.dataset_version,rubric_version:manifest.rubric_version,protocol_version:manifest.protocol_version,status:next,config:{...manifest},config_hash:require('../lib/researchStudy').studyManifestHash({study_id:studyId,study_version:manifest.study_version,datasetVersion:manifest.dataset_version,rubricVersion:manifest.rubric_version,protocolVersion:manifest.protocol_version,candidateSnapshot:manifest.candidate_snapshot||'pending',pilotCases:manifest.pilot_cases,mainCases:manifest.main_cases,developmentCases:manifest.development_cases,validationCases:manifest.validation_cases,lockedTestCases:manifest.locked_test_cases,minimumIndependentRaters:manifest.minimum_independent_raters,hiddenDuplicateRate:manifest.hidden_duplicate_rate}),updated_at:now,created_by:row?.created_by||user.id,locked_at:['DATASET_FROZEN','CANDIDATES_FROZEN','MAIN_ANNOTATION'].includes(next)?now:null};const r=row?await rest(`thinkforge_research_studies?study_id=eq.${esc(studyId)}`,'PATCH',payload):await rest('thinkforge_research_studies','POST',{...payload,created_at:now});if(!r.ok)throw new Error(await r.text());return res.status(200).json({studyId,status:next,requestId:rid});}
 if(b.action==='pairwise'){const allowed=new Set(['A','B','TIE']);const pref=String(b.preference||'').toUpperCase();if(!allowed.has(pref))return res.status(400).json({error:'Invalid preference',requestId:rid});const row={study_id:studyId,case_id:String(b.caseId),rater_id:user.id,left_candidate:String(b.leftCandidate||'A'),preference:pref,position_seed:String(b.positionSeed||'server'),blinded:b.blinded!==false,created_at:new Date().toISOString()};const r=await rest('thinkforge_evaluation_pairwise_v2','POST',row);if(!r.ok)throw new Error(await r.text());return res.status(201).json({ok:true,requestId:rid});}
 if(b.action==='impact'){const condition=String(b.condition);if(!['HUMAN_ONLY','HUMAN_PLUS_THINKFORGE'].includes(condition))return res.status(400).json({error:'Invalid condition',requestId:rid});const row={study_id:studyId,participant_id:user.id,scenario_id:String(b.scenarioId),condition,decision_quality:Number(b.decisionQuality),decision_time_seconds:Number(b.decisionTimeSeconds||0),assumptions_found:Number(b.assumptionsFound||0),evidence_used:Number(b.evidenceUsed||0),confidence:Number(b.confidence||3),notes:String(b.notes||'').slice(0,5000),created_at:new Date().toISOString()};const r=await rest('thinkforge_decision_impact_records','POST',row);if(!r.ok)throw new Error(await r.text());return res.status(201).json({ok:true,requestId:rid});}
 return res.status(400).json({error:'Unsupported research action',requestId:rid});
}catch(e){return res.status(e.status||502).json({error:e.message||'Research action failed',code:e.code||'RESEARCH_ACTION_FAILED',requestId:rid});}};
