'use strict';
const fs=require('node:fs'),path=require('node:path');
const {requireUser,requestId}=require('../lib/auth');
const {limit}=require('../lib/rateLimit');
const {applySecurityHeaders,bodySizeOk}=require('../lib/security');
const {rest}=require('../lib/db');
const {makeStudy,transition,canAnnotate,requireFrozenStudy}=require('../lib/researchStudy');
const {pilotSummary,qualify,certify}=require('../lib/annotationQualification');
const bench=JSON.parse(fs.readFileSync(path.join(__dirname,'..','eval','benchmark_300.json'),'utf8'));
const rubric=require('../eval/rubrics.json');
async function db(pathname,method='GET',body){return rest(pathname,method,body)}
async function getRater(userId,studyId){const r=await db(`thinkforge_evaluation_rater_profiles?rater_id=eq.${encodeURIComponent(userId)}&study_id=eq.${encodeURIComponent(studyId)}&select=*`);if(!r.ok)return null;const j=await r.json();return j?.[0]||null}
module.exports=async function(req,res){applySecurityHeaders(res);const rid=requestId(req);res.setHeader('x-request-id',rid);if(req.method!=='POST')return res.status(405).json({error:'Method not allowed',requestId:rid});if(!bodySizeOk(req))return res.status(413).json({error:'Body too large',requestId:rid});const user=await requireUser(req,res);if(!user)return;const rl=await limit(req,{scope:'study',max:60,windowMs:60000});if(!rl.ok)return res.status(429).json({error:'Rate limited',requestId:rid});const b=req.body||{};const studyId=String(b.studyId||'HG-001');
try{
 if(b.action==='config'){return res.status(200).json({study:makeStudy({id:studyId,datasetVersion:bench.version,rubricVersion:rubric.version}),benchmark:{cases:bench.cases.length,lockedTest:180},rubric:{version:rubric.version},requestId:rid});}
 if(b.action==='rater'){const existing=await getRater(user.id,studyId);return res.status(200).json({rater:existing||{study_id:studyId,rater_id:user.id,qualification_status:'UNTRAINED',pilot_completed:0,pilot_quality:null,hidden_duplicate_consistency:null,certified_at:null},requestId:rid});}
 if(b.action==='transition'){const r=await getRater(user.id,studyId);const current=r?.qualification_status||'UNTRAINED';const next=transition(current,String(b.nextState));const payload={study_id:studyId,rater_id:user.id,qualification_status:next,updated_at:new Date().toISOString()};const rr=r?await db(`thinkforge_evaluation_rater_profiles?rater_id=eq.${encodeURIComponent(user.id)}&study_id=eq.${encodeURIComponent(studyId)}`,'PATCH',payload):await db('thinkforge_evaluation_rater_profiles','POST',{...payload,created_at:new Date().toISOString()});if(!rr.ok)throw new Error(await rr.text());return res.status(200).json({state:next,canAnnotate:canAnnotate(next),requestId:rid});}
 if(b.action==='pilot'){const r=await getRater(user.id,studyId);const summary=pilotSummary({completed:Number(b.completed||r?.pilot_completed||0),required:30,qualityScore:Number(b.qualityScore??r?.pilot_quality??0),hiddenDuplicateConsistency:Number(b.hiddenDuplicateConsistency??r?.hidden_duplicate_consistency??0),attentionCheckRate:Number(b.attentionCheckRate??r?.attention_check_rate??1)});const rr=await db(`thinkforge_evaluation_rater_profiles?rater_id=eq.${encodeURIComponent(user.id)}&study_id=eq.${encodeURIComponent(studyId)}`,'PATCH',{pilot_completed:summary.completed,quality_score:summary.quality,hidden_duplicate_consistency:summary.hidden,attention_check_rate:summary.attention,updated_at:new Date().toISOString()});if(!rr.ok)throw new Error(await rr.text());return res.status(200).json({pilot:summary,requestId:rid});}
 if(b.action==='qualify'){const r=await getRater(user.id,studyId);const result=qualify({state:r?.qualification_status||'UNTRAINED',pilot:{completed:r?.pilot_completed||0,qualityScore:r?.pilot_quality||0,hiddenDuplicateConsistency:r?.hidden_duplicate_consistency||0}});if(result.eligible){const rr=await db(`thinkforge_evaluation_rater_profiles?rater_id=eq.${encodeURIComponent(user.id)}&study_id=eq.${encodeURIComponent(studyId)}`,'PATCH',{qualification_status:result.state,updated_at:new Date().toISOString()});if(!rr.ok)throw new Error(await rr.text());}return res.status(200).json({...result,requestId:rid});}
 if(b.action==='certify'){const r=await getRater(user.id,studyId);const result=certify({state:r?.qualification_status||'UNTRAINED',reviewPassed:Boolean(b.reviewPassed)});if(result.certified){const rr=await db(`thinkforge_evaluation_rater_profiles?rater_id=eq.${encodeURIComponent(user.id)}&study_id=eq.${encodeURIComponent(studyId)}`,'PATCH',{qualification_status:result.state,certified_at:new Date().toISOString(),updated_at:new Date().toISOString()});if(!rr.ok)throw new Error(await rr.text());}return res.status(200).json({...result,requestId:rid});}
 return res.status(400).json({error:'Unsupported study action',code:'INVALID_ACTION',requestId:rid});
}catch(e){return res.status(e.status||502).json({error:e.message||'Study action failed',code:e.code||'STUDY_ACTION_FAILED',requestId:rid});}};
